trigger:
- main  # Runs the pipeline when code is pushed to the main branch

pool:
  vmImage: 'windows-latest'  # Use Windows for IIS deployment

steps:
# Step 1: Checkout the repository
- checkout: self

# Step 2: Install Node.js
- task: UseNode@1
  displayName: 'Use Node.js'
  inputs:
    version: '18.x'  # Use a version compatible with your React project

# Step 3: Install dependencies
- script: npm install
  displayName: 'Install Dependencies'

# Step 4: Build the React application
- script: npm run build
  displayName: 'Build React App'
  env:
    CI: false  # Prevents CI from failing on warnings

# Step 5: Publish Build Artifacts (React build folder)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathToPublish: 'build'  # React builds to 'build' by default
    artifactName: 'drop'

# Step 6: Deploy to IIS (Add IIS Deployment Step Here if Needed)
